routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/update_feed', 'FeedController@update')
    ->name('feed.update');

Route::get('/', 'FeedController@index')
    ->name('feed.index');

Route::get('/view/{id}', 'FeedController@view')
    ->name('feed.view');

/** add comment route */
Route::post('/view/{id}', 'FeedController@comment')
    ->name('feed.comment.new');

Route::get('/edit/{id}', 'FeedController@edit')
    ->name('feed.edit');

Route::post('/edit/{id}', 'FeedController@editPost')
    ->name('feed.edit.save');

Route::get('/remove/{id}', 'FeedController@delete')
    ->name('feed.remove');

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


/**
 * Comment model
 *
 * Class Comment
 * @package App\Models
 */
class Comment extends Model
{
    /** @var array list of names of fields wich would be protected of mass asignment */
    protected $guarded = [];

    public function feed()
    {
        return $this->belongsTo('App\Models\Feed');
    }
}

app/Models/Feed.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


/**
 * Just Feed model
 *
 * Class Feed
 * @package App\Models
 */
class Feed extends Model
{
    /** @var array list of names of fields wich would be protected of mass asignment */
    protected $guarded = [];

    public function comments()
    {
        return $this->hasMany('App\Models\Comment');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;


/**
 * Base User model, untouched
 *
 * Class User
 * @package App\Models
 */
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FeedController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Models\Feed;
use Carbon\Carbon;
use Illuminate\Http\Request;


/**
 * Manipuliting with our "nasa rss feed"
 *
 * Class FeedController
 * @package App\Http\Controllers
 */
class FeedController extends Controller
{
    /** @var string link to xml document */
    protected $feedUrl = 'https://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss';

    /**
     * parse url and save data to Feeds table
     * pretty ugly, but works
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update()
    {
        $feed = simplexml_load_file($this->feedUrl);

        $items = [];
        $dates = [];

        foreach($feed->channel->item as $item) {
            $item->enclosure = $item->enclosure->attributes()->url;
            $item->pubDate = Carbon::createFromFormat('D, d M Y H:i T', $item->pubDate)->toDateTimeString();
            unset($item->guid);
            unset($item->source);
            $items[] = (array)$item;
            $dates[] = (string)$item->pubDate;
        }

        array_multisort($dates, SORT_ASC, $items);

        foreach ($items as $item){
            Feed::firstOrCreate((array)$item);
        }
        return redirect()->route('feed.index');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $feeds = Feed::orderBy('pubDate', 'desc')->withCount('comments')->get();
        return view('feeds', compact('feeds'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function view($id)
    {
        $feed = Feed::with('comments')->find($id);
        return view('feed', compact('feed'));
    }

    /**
     * validate and save comment
     *
     * @param Request $request
     * @param Comment $comment
     * @param         $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function comment(Request $request, Comment $comment, $id)
    {
        $this->validate($request, [
            'user' => 'required|max:191',
            'text' => 'required',
        ]);

        $comment->feed_id = $id;
        $comment->fill($request->all())->save();

        return redirect()->route('feed.view', $id);
    }

    /**
     * form to edit single feed parts
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $feed = Feed::find($id);
        return view('edit', compact('feed'));
    }

    /**
     * validate and save edited feed
     *
     * @param Request $request
     * @param         $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function editPost(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required|max:191',
            'description' => 'required',
        ]);

        $feed = Feed::find($id);
        $feed->fill($request->all())->save();

        return redirect()->route('feed.view', $id);
    }

    /**
     * remove single feed from db
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete($id)
    {
        Feed::destroy($id);

        return redirect()->route('feed.index');
    }
}

resources/views/edit.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ $feed->title }}</title>
    </head>
    <body>
        <form method="post">
            <p>You can edit title and description</p>
            {{ csrf_field() }}
            <label for="title">Title</label>
            {{ $errors->first('title') ?? '' }}<br>
            <input type="text" size="80" id="title" name="title" value="{{ old('title', $feed->title) }}"><br>
            <label for="description">Description</label>
            {{ $errors->first('description') ?? '' }}<br>
            <textarea cols="80" rows="10" id="description" name="description">{{ old('description', $feed->description) }}</textarea><br>
            <button>Save</button>
        </form>
    </body>
</html>

resources/views/feed.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ $feed->title }}</title>
    </head>
    <body>
        {{ $feed->title }}<br>
        <img src="{{ $feed->enclosure }}"><br>
        {{ $feed->description }}<br>
        <a href="{{ $feed->link }}">Original</a><br>
        <hr>
        <form method="post">
            <p>You can say something about this</p>
            {{ csrf_field() }}
            <label for="user">Your name</label>
            {{ $errors->first('user') ?? '' }}<br>
            <input type="text" id="user" name="user" value="{{ old('user', 'Guest') }}"><br>
            <label for="text">What are you thinking about?</label>
            {{ $errors->first('text') ?? '' }}<br>
            <textarea cols="80" rows="10" id="text" name="text">{{ old('text') }}</textarea><br>
            <button>Comment</button>
        </form>
        @forelse($feed->comments as $comment)
            <hr>
            {{ $comment->user }} wrote ({{ $comment->created_at }}):<br>
            {{ $comment->text }}<br>
        @empty
            <p>No comments yet. You can be first</p>
        @endforelse
    </body>
</html>

resources/views/feeds.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Nasa image of the day</title>
    </head>
    <body>
        <table>
            <tr>
                <td>ID</td>
                <td>Actions</td>
                <td>Title</td>
                <td>Publication date</td>
                <td>Upload date</td>
                <td>Comments</td>
            </tr>
            @foreach($feeds as $feed)
                <tr>
                    <td>{{ $feed->id }}</td>
                    <td><a href="{{ route('feed.edit', $feed->id) }}">Edit</a> or <a href="{{ route('feed.remove', $feed->id) }}">Remove</a></td>
                    <td><a href="{{ route('feed.view', $feed->id) }}">{{ $feed->title }}</a></td>
                    <td><a href="{{ $feed->link }}">{{ $feed->pubDate }}</a></td>
                    <td>{{ $feed->created_at }}</td>
                    <td>{{ $feed->comments_count }}</td>
                </tr>
            @endforeach
        </table>
    </body>
</html>